name: test

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19.x', '1.20.x', '1.21.x']
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
